version: 2.1

orbs:
  node: circleci/node@5.0.2
  sonarcloud: sonarsource/sonarcloud@1.1.0
  codecov: codecov/codecov@3.2.2

jobs:
  build_and_test:
    docker:
      - image: vernaillen/circleci-pnpm:18.2.0
    steps:
      - checkout
      - run:
          name: Install packages
          command: pnpm install --frozen-lockfile
      - run:
          name: Lint
          command: pnpm run lint
      - run:
          name: Test
          command: pnpm test
      - sonarcloud/scan
      - run:
          name: Build
          command: |
            pnpm run build
            ls dist
  trigger_deploy:
    executor: 
      name: node/default
    steps:
      - run:
          name: Trigger Netlify Deploy
          command: curl -X POST -d {} ${NETLIFY_HOOK}

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test:
          context: SonarCloud
          post-steps:
            - codecov/upload:
                file: ./coverage/lcov.info
      - trigger_deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - master

