version: 2.1

orbs:
  node: circleci/node@5.0.2
  sonarcloud: sonarsource/sonarcloud@1.0.3
  codecov: codecov/codecov@3.2.2

jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - sonarcloud/scan
      - run:
          command: npm run build
      - run:
          command: npm run coverage
      - store_test_results:
          path: test-results

workflows:
  build-test:
    jobs:
      - test:
          context: SonarCloud
          post-steps:
            - codecov/upload
